In [4]:
import pandas as pd
from pathlib import Path

In [11]:
file_path = Path("../data/processed")
df = pd.read_csv(file_path/"cyclistic_2019_cleaned.csv")
sample = pd.read_csv(file_path/"cyclistic_2019_cleaned.csv", nrows=10000)

sample.shape

(10000, 18)

In [7]:
sample.columns.tolist()

['trip_id',
 'start_time',
 'end_time',
 'bikeid',
 'tripduration',
 'from_station_id',
 'from_station_name',
 'to_station_id',
 'to_station_name',
 'usertype',
 'gender',
 'birthyear',
 'rider_type',
 'trip_duration_minutes',
 'day_of_week',
 'month',
 'hour',
 'season']

In [8]:
sample.dtypes

trip_id                    int64
start_time                   str
end_time                     str
bikeid                     int64
tripduration             float64
from_station_id            int64
from_station_name            str
to_station_id              int64
to_station_name              str
usertype                     str
gender                       str
birthyear                float64
rider_type                   str
trip_duration_minutes    float64
day_of_week                  str
month                      int64
hour                       int64
season                       str
dtype: object

In [9]:
sample.head()

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear,rider_type,trip_duration_minutes,day_of_week,month,hour,season
0,21742443,2019-01-01 00:04:37,2019-01-01 00:11:07,2167,390.0,199,Wabash Ave & Grand Ave,84,Milwaukee Ave & Grand Ave,Subscriber,Male,1989.0,Annual Member,6.500000,Tuesday,1,0,Winter
1,21742444,2019-01-01 00:08:13,2019-01-01 00:15:34,4386,441.0,44,State St & Randolph St,624,Dearborn St & Van Buren St (*),Subscriber,Female,1990.0,Annual Member,7.350000,Tuesday,1,0,Winter
2,21742445,2019-01-01 00:13:23,2019-01-01 00:27:12,1524,829.0,15,Racine Ave & 18th St,644,Western Ave & Fillmore St (*),Subscriber,Female,1994.0,Annual Member,13.816667,Tuesday,1,0,Winter
3,21742446,2019-01-01 00:13:45,2019-01-01 00:43:28,252,1783.0,123,California Ave & Milwaukee Ave,176,Clark St & Elm St,Subscriber,Male,1993.0,Annual Member,29.716667,Tuesday,1,0,Winter
4,21742447,2019-01-01 00:14:52,2019-01-01 00:20:56,1170,364.0,173,Mies van der Rohe Way & Chicago Ave,35,Streeter Dr & Grand Ave,Subscriber,Male,1994.0,Annual Member,6.066667,Tuesday,1,0,Winter

In [10]:
sample.isna().sum()

trip_id                    0
start_time                 0
end_time                   0
bikeid                     0
tripduration               0
from_station_id            0
from_station_name          0
to_station_id              0
to_station_name            0
usertype                   0
gender                   438
birthyear                388
rider_type                 0
trip_duration_minutes      0
day_of_week                0
month                      0
hour                       0
season                     0
dtype: int64

In [12]:
df.shape

(3818004, 18)

In [14]:
df.isna().sum()

trip_id                       0
start_time                    0
end_time                      0
bikeid                        0
tripduration                  0
from_station_id               0
from_station_name             0
to_station_id                 0
to_station_name               0
usertype                      0
gender                   559206
birthyear                538751
rider_type                    0
trip_duration_minutes         0
day_of_week                   0
month                         0
hour                          0
season                        0
dtype: int64

In [15]:
df["rider_type"].value_counts()

rider_type
Annual Member    2937367
Casual Rider      880637
Name: count, dtype: int64

In [16]:
df["start_time"] = pd.to_datetime(df["start_time"])
df["end_time"] = pd.to_datetime(df["end_time"])

df[["start_time", "end_time"]].dtypes

start_time    datetime64[us]
end_time      datetime64[us]
dtype: object

In [17]:
df[["start_time", "end_time"]].agg(["min", "max"])

             start_time            end_time
min 2019-01-01 00:04:37 2019-01-01 00:11:07
max 2019-12-31 23:57:17 2020-01-21 13:54:35

In [18]:
tableau_columns = [
    "trip_id",
    "start_time",
    "from_station_id",
    "from_station_name",
    "to_station_id",
    "to_station_name",
    "rider_type",
    "trip_duration_minutes",
    "day_of_week",
    "month",
    "hour",
    "season"
]

In [19]:
df["trip_duration_minutes"].describe(
    percentiles=[.01, .25, .5, .75, .95, .99]
)

count    3.818004e+06
mean     2.417006e+01
std      4.975691e+02
min      1.016667e+00
1%       2.133333e+00
25%      6.850000e+00
50%      1.181667e+01
75%      2.138333e+01
95%      5.356667e+01
99%      1.254833e+02
max      1.771400e+05
Name: trip_duration_minutes, dtype: float64

In [20]:
df.nlargest(10, "trip_duration_minutes")[
    ["trip_id", "start_time", "rider_type", "trip_duration_minutes"]
]

          trip_id          start_time     rider_type  trip_duration_minutes
148897   21920842 2019-02-14 14:44:13   Casual Rider          177140.000000
1753537  23798837 2019-07-16 18:17:58  Annual Member          150943.883333
3189137  25302386 2019-10-06 13:57:02   Casual Rider          143098.366667
1839638  23889502 2019-07-22 12:09:36  Annual Member          136727.283333
3367117  25487192 2019-10-19 15:14:50   Casual Rider          135339.750000
1669835  23710210 2019-07-12 13:08:10   Casual Rider          132324.133333
2047113  24107150 2019-08-01 18:45:47   Casual Rider          127791.150000
1630590  23661214 2019-07-10 10:25:13   Casual Rider          126781.183333
1618591  23648641 2019-07-09 17:28:05   Casual Rider          125367.700000
1756534  23801970 2019-07-16 20:44:13   Casual Rider          123677.200000

In [ ]:
for threshold in [60, 120, 180, 360, 720, 1440]:
    count = (df["trip_duration_minutes"] > threshold).sum()
    pct = count / len(df) * 100

    print(
        f"> {threshold:4} min: "
        f"{count:>8,} rides ({pct:.3f}%)"
    )

>   60 min:  157,720 rides (4.131%)
>  120 min:   42,533 rides (1.114%)
>  180 min:   14,146 rides (0.371%)
>  360 min:    6,136 rides (0.161%)
>  720 min:    3,945 rides (0.103%)
> 1440 min:    1,848 rides (0.048%)

In [22]:
df.groupby("rider_type")["trip_duration_minutes"].agg(
    ["count", "mean", "median", "max"]
)

                 count       mean     median            max
rider_type
Annual Member  2937367  14.323055   9.800000  150943.883333
Casual Rider    880637  57.014762  25.816667  177140.000000

In [23]:
tableau_df = df[
    df["trip_duration_minutes"] <= 1440
].copy()

tableau_df.shape

(3816156, 18)

In [24]:
tableau_df.groupby("rider_type")["trip_duration_minutes"].agg(
    ["count", "mean", "median", "max"]
)

                 count       mean     median      max
rider_type
Annual Member  2936866  12.927207   9.800000  1439.75
Casual Rider    879290  39.425583  25.783333  1440.00

In [25]:
tableau_columns = [
    "trip_id",
    "start_time",
    "from_station_id",
    "from_station_name",
    "to_station_id",
    "to_station_name",
    "rider_type",
    "trip_duration_minutes",
    "day_of_week",
    "month",
    "hour",
    "season"
]

tableau_df = tableau_df[tableau_columns].copy()

tableau_df.info()

<class 'pandas.DataFrame'>
Index: 3816156 entries, 0 to 3818003
Data columns (total 12 columns):
 #   Column                 Dtype
---  ------                 -----
 0   trip_id                int64
 1   start_time             datetime64[us]
 2   from_station_id        int64
 3   from_station_name      str
 4   to_station_id          int64
 5   to_station_name        str
 6   rider_type             str
 7   trip_duration_minutes  float64
 8   day_of_week            str
 9   month                  int64
 10  hour                   int64
 11  season                 str
dtypes: datetime64[us](1), float64(1), int64(5), str(5)
memory usage: 378.5 MB

In [26]:
tableau_df["hour_label"] = pd.to_datetime(
    tableau_df["hour"],
    format="%H"
).dt.strftime("%-I %p")

In [27]:
tableau_df[["hour", "hour_label"]].drop_duplicates().sort_values("hour")

      hour hour_label
0        0      12 AM
41       1       1 AM
89       2       2 AM
126      3       3 AM
143      4       4 AM
153      5       5 AM
160      6       6 AM
173      7       7 AM
194      8       8 AM
223      9       9 AM
284     10      10 AM
360     11      11 AM
448     12      12 PM
550     13       1 PM
643     14       2 PM
717     15       3 PM
833     16       4 PM
965     17       5 PM
1049    18       6 PM
1132    19       7 PM
1194    20       8 PM
1237    21       9 PM
1264    22      10 PM
1296    23      11 PM

In [28]:
tableau_df.info()

<class 'pandas.DataFrame'>
Index: 3816156 entries, 0 to 3818003
Data columns (total 13 columns):
 #   Column                 Dtype
---  ------                 -----
 0   trip_id                int64
 1   start_time             datetime64[us]
 2   from_station_id        int64
 3   from_station_name      str
 4   to_station_id          int64
 5   to_station_name        str
 6   rider_type             str
 7   trip_duration_minutes  float64
 8   day_of_week            str
 9   month                  int64
 10  hour                   int64
 11  season                 str
 12  hour_label             str
dtypes: datetime64[us](1), float64(1), int64(5), str(6)
memory usage: 407.6 MB

In [31]:
output_path = file_path / "cyclistic_2019_tableau.csv"

tableau_df.to_csv(output_path, index=False)

In [32]:
file_size_mb = output_path.stat().st_size / (1024 ** 2)

print(f"Tableau dataset: {file_size_mb:.1f} MB")

Tableau dataset: 502.8 MB